// Generated by CoffeeScript 1.3.3
(function() {
  var Hogan, fs, getTemplates;

  fs = require('fs');

  Hogan = require('hogan.js');

  getTemplates = function(sharedDir, ext) {
    var exportTemplate, fetchTemplates, getDirFiles, templates;
    if (ext == null) {
      ext = "html";
    }
    templates = [];
    exportTemplate = Hogan.compile(fs.readFileSync(__dirname + "/../views/templates.js.mustache", "utf8"));
    getDirFiles = function(dir) {
      return fs.readdirSync(dir);
    };
    fetchTemplates = function(dir) {
      var file, ns, path, template, _i, _len, _ref, _results;
      _ref = getDirFiles(dir);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        if (file.substr(file.length - 5) === ("." + ext)) {
          path = dir + '/' + file;
          ns = path.replace(sharedDir, '').substr(1).replace("." + ext, '');
          template = Hogan.compile(fs.readFileSync(path, "utf8"), {
            asString: true
          });
          _results.push(templates.push({
            file: path,
            ns: ns.replace(/(\/)/g, '.'),
            template: template
          }));
        } else {
          _results.push(fetchTemplates("" + dir + "/" + file));
        }
      }
      return _results;
    };
    fetchTemplates(sharedDir);
    if (templates.length !== 0) {
      templates[templates.length - 1].last = true;
    }
    return exportTemplate.render({
      templates: templates
    });
  };

  exports.getTemplates = getTemplates;

}).call(this);
